// #################################################
// ###### THIS FILE IS AUTOMATICALLY GENERATED #####
// ########      DO NOT EDIT BY HAND     ###########
// #################################################

#[path = "./client/0_set_protocol.rs"]
mod set_protocol;
pub use set_protocol::*;

#[path = "./client/254_legacy_server_list_ping.rs"]
mod legacy_server_list_ping;
pub use legacy_server_list_ping::*;
