// #################################################
// ###### THIS FILE IS AUTOMATICALLY GENERATED #####
// ########      DO NOT EDIT BY HAND     ###########
// #################################################

#[path = "./client/0_keep_alive.rs"]
mod keep_alive;
pub use keep_alive::*;

#[path = "./client/1_chat.rs"]
mod chat;
pub use chat::*;

#[path = "./client/2_use_entity.rs"]
mod use_entity;
pub use use_entity::*;

#[path = "./client/3_flying.rs"]
mod flying;
pub use flying::*;

#[path = "./client/4_position.rs"]
mod position;
pub use position::*;

#[path = "./client/5_look.rs"]
mod look;
pub use look::*;

#[path = "./client/6_position_and_look.rs"]
mod position_and_look;
pub use position_and_look::*;

#[path = "./client/9_held_item_slot.rs"]
mod held_item_slot;
pub use held_item_slot::*;

#[path = "./client/10_arm_animation.rs"]
mod arm_animation;
pub use arm_animation::*;

#[path = "./client/13_close_window.rs"]
mod close_window;
pub use close_window::*;

#[path = "./client/15_transaction.rs"]
mod transaction;
pub use transaction::*;

#[path = "./client/21_client_settings.rs"]
mod client_settings;
pub use client_settings::*;

#[path = "./client/22_client_command.rs"]
mod client_command;
pub use client_command::*;
