// #################################################
// ###### THIS FILE IS AUTOMATICALLY GENERATED #####
// ########      DO NOT EDIT BY HAND     ###########
// #################################################

#[path = "./server/0_keep_alive.rs"]
mod keep_alive;
pub use keep_alive::*;

#[path = "./server/1_login.rs"]
mod login;
pub use login::*;

#[path = "./server/2_chat.rs"]
mod chat;
pub use chat::*;

#[path = "./server/3_update_time.rs"]
mod update_time;
pub use update_time::*;

#[path = "./server/5_spawn_position.rs"]
mod spawn_position;
pub use spawn_position::*;

#[path = "./server/6_update_health.rs"]
mod update_health;
pub use update_health::*;

#[path = "./server/7_respawn.rs"]
mod respawn;
pub use respawn::*;

#[path = "./server/8_position.rs"]
mod position;
pub use position::*;

#[path = "./server/9_held_item_slot.rs"]
mod held_item_slot;
pub use held_item_slot::*;

#[path = "./server/10_bed.rs"]
mod bed;
pub use bed::*;

#[path = "./server/11_animation.rs"]
mod animation;
pub use animation::*;

#[path = "./server/13_collect.rs"]
mod collect;
pub use collect::*;

#[path = "./server/16_spawn_entity_painting.rs"]
mod spawn_entity_painting;
pub use spawn_entity_painting::*;

#[path = "./server/17_spawn_entity_experience_orb.rs"]
mod spawn_entity_experience_orb;
pub use spawn_entity_experience_orb::*;

#[path = "./server/18_entity_velocity.rs"]
mod entity_velocity;
pub use entity_velocity::*;

#[path = "./server/19_entity_destroy.rs"]
mod entity_destroy;
pub use entity_destroy::*;

#[path = "./server/20_entity.rs"]
mod entity;
pub use entity::*;

#[path = "./server/21_entity_relative_move.rs"]
mod entity_relative_move;
pub use entity_relative_move::*;

#[path = "./server/22_entity_look.rs"]
mod entity_look;
pub use entity_look::*;

#[path = "./server/23_entity_move_look.rs"]
mod entity_move_look;
pub use entity_move_look::*;

#[path = "./server/24_entity_teleport.rs"]
mod entity_teleport;
pub use entity_teleport::*;

#[path = "./server/25_entity_head_rotation.rs"]
mod entity_head_rotation;
pub use entity_head_rotation::*;

#[path = "./server/26_entity_status.rs"]
mod entity_status;
pub use entity_status::*;

#[path = "./server/27_attach_entity.rs"]
mod attach_entity;
pub use attach_entity::*;

#[path = "./server/28_entity_metadata.rs"]
mod entity_metadata;
pub use entity_metadata::*;

#[path = "./server/29_entity_effect.rs"]
mod entity_effect;
pub use entity_effect::*;

#[path = "./server/30_remove_entity_effect.rs"]
mod remove_entity_effect;
pub use remove_entity_effect::*;

#[path = "./server/35_block_change.rs"]
mod block_change;
pub use block_change::*;

#[path = "./server/64_kick_disconnect.rs"]
mod kick_disconnect;
pub use kick_disconnect::*;
