// #################################################
// ###### THIS FILE IS AUTOMATICALLY GENERATED #####
// ########      DO NOT EDIT BY HAND     ###########
// #################################################

#[path = "./server/0_disconnect.rs"]
mod disconnect;
pub use disconnect::*;

#[path = "./server/2_login_success.rs"]
mod login_success;
pub use login_success::*;

#[path = "./server/3_set_compression.rs"]
mod set_compression;
pub use set_compression::*;
