// #################################################
// ###### THIS FILE IS AUTOMATICALLY GENERATED #####
// ########      DO NOT EDIT BY HAND     ###########
// #################################################

#[path = "./client/0_ping_start.rs"]
mod ping_start;
pub use ping_start::*;

#[path = "./client/1_ping.rs"]
mod ping;
pub use ping::*;
