// #################################################
// ###### THIS FILE IS AUTOMATICALLY GENERATED #####
// ########      DO NOT EDIT BY HAND     ###########
// #################################################

#[path = "./server/0_server_info.rs"]
mod server_info;
pub use server_info::*;

#[path = "./server/1_ping.rs"]
mod ping;
pub use ping::*;
